# Generated by Django 6.1.2 on 2026-10-09 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_hash', models.CharField(max_length=64, verbose_name='хеш текста')),
                ('model_name', models.CharField(max_length=255, verbose_name='имя модели')),
                ('vector', models.JSONField(verbose_name='вектор')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='catalog.site', verbose_name='площадка')),
            ],
            options={
                'verbose_name': 'эмбеддинг площадки',
                'verbose_name_plural': 'эмбеддинги площадок',
                'ordering': ['site_id', 'model_name', 'text_hash'],
                'constraints': [models.UniqueConstraint(fields=('site', 'text_hash', 'model_name'), name='site_embedding_site_hash_model_uniq')],
            },
        ),
    ]
