# Generated by Django 5.2.18 on 2026-10-08 06:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('treatment_profile', models.CharField(max_length=255, verbose_name='профиль лечения')),
            ],
            options={
                'verbose_name': 'учреждение',
                'verbose_name_plural': 'учреждения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='адрес')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='долгота')),
                ('transport_accessibility', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Оценка от 1 до 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='транспортная доступность')),
                ('min_daily_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='минимальная цена за сутки')),
                ('max_daily_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='максимальная цена за сутки')),
                ('procedures', models.TextField(verbose_name='текст процедур')),
                ('excursions', models.TextField(verbose_name='текст экскурсий')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='catalog.institution', verbose_name='учреждение')),
            ],
            options={
                'verbose_name': 'площадка',
                'verbose_name_plural': 'площадки',
                'ordering': ['address'],
                'constraints': [models.CheckConstraint(condition=models.Q(('transport_accessibility__gte', 1), ('transport_accessibility__lte', 5)), name='site_transport_accessibility_between_1_and_5'), models.CheckConstraint(condition=models.Q(('min_daily_price__lte', models.F('max_daily_price'))), name='site_min_daily_price_lte_max_daily_price'), models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='site_latitude_range'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='site_longitude_range')],
            },
        ),
    ]
