# Generated by Django 6.1.2 on 2026-10-09 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='limited_mobility_access',
            field=models.BooleanField(default=False, help_text='Есть условия для людей с ограниченной подвижностью.', verbose_name='доступность для маломобильных'),
        ),
        migrations.AddField(
            model_name='site',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'не указан'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, help_text='Оценка от 0 до 5. 0 — рейтинг не указан.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='рейтинг'),
        ),
        migrations.AddField(
            model_name='site',
            name='season',
            field=models.CharField(choices=[('year_round', 'круглый год'), ('spring', 'весна'), ('summer', 'лето'), ('autumn', 'осень'), ('winter', 'зима')], default='year_round', help_text='Когда площадка принимает гостей.', max_length=32, verbose_name='сезон'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(error_messages={'unique': 'Учреждение с таким названием уже есть.'}, max_length=255, unique=True, verbose_name='название'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='site_rating_between_0_and_5', violation_error_message='Рейтинг должен быть от 0 до 5.'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.CheckConstraint(condition=models.Q(('season__in', ('year_round', 'spring', 'summer', 'autumn', 'winter'))), name='site_season_known', violation_error_message='Сезон должен быть одним из известных значений.'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('institution', 'address'), name='site_institution_address_uniq', violation_error_message='У этого учреждения уже есть площадка с таким адресом.'),
        ),
    ]
