# Generated by Django 5.2.18 on 2026-10-08 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_text', models.TextField(verbose_name='текст маршрута')),
                ('sites', models.ManyToManyField(related_name='plans', to='catalog.site', verbose_name='площадки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'план',
                'verbose_name_plural': 'планы',
                'ordering': ['-id'],
            },
        ),
    ]
